apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nfs-storage
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
    server: 192.168.1.200
    share: /mnt/data3/nfs
reclaimPolicy: Retain