apiVersion: v1
kind: Pod
metadata:
    name: pod
    namespace: homework
spec:
    initContainers:
      - name: init-container
        image: busybox:1.36
        command:
          - /bin/sh
          - -c
          - |
              wget -O /init/index.html https://google.com/index.html
        volumeMounts:
          - name: media-volume
            mountPath: /init
    containers:
      - name: nginx-container
        image: nginx:1.25-alpine
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
            limits:
                cpu: "1"
                memory: "256M"
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d
          - name: media-volume
            mountPath: /homework
        lifecycle:
            preStop:
                exec:
                    command:
                      - /bin/sh
                      - -c
                      - |
                          rm -f /homework/index.html
                        
    volumes:
      - name: nginx-config-volume
        configMap:
            name: nginx-config
      - name: media-volume
        emptyDir: {}
          
        